name = "NewtonsMethod"
uuid = "18e7d761-5163-463c-89ae-8ae6edff33ab"
authors = ["Tsuyoshi Matsuura"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ForwardDiff = "1.0.1"
LinearAlgebra = "1.11.0"
julia = "1.11"
